import { CaseLabel, CaseOpening, CaseStudyShell } from "@/components/case-study";
import { SiteHeader } from "@/components/site-header";
import type { Metadata } from "next";
import styles from "./case-106-refinement.module.css";

export const metadata: Metadata = { title: "I Already Told You This — Rotem Kasahun" };
const currentFlow = ["Write issue + location", "Generic intake", "Repeat issue", "Complete the remaining fields", "Submit"];
const betterFlow = ["Write issue + location", "Use what’s already there", "Ask only for what’s missing", "Submit"];
const checksBeforeBuilding = ["Which fields are actually mandatory?", "At what point does a WhatsApp message become an official 106 request?", "What information can the existing WhatsApp and service-management setup already receive automatically?", "Which requests should always go to a human?"];
const checksIfPiloted = ["Does it reduce the number of messages needed to submit a request?", "Do more residents complete the flow?", "Can issue and location be extracted accurately enough?"];

export default function IAlreadyToldYouThis() {
  return <CaseStudyShell className={`case-106 ${styles.rebuild}`}><div className="golda-header-shell"><SiteHeader /></div>
    <CaseOpening><div className="case106-opening-copy"><CaseLabel>A real-life annoyance / service design / 2026</CaseLabel><h1><span className="motion-headline-line">I Already Told You This</span></h1><p className="case106-intro">I told the city what was wrong.</p><p className="case106-intro">I told them where it was.</p><p className="case106-intro">Then their WhatsApp asked me to do it again.</p><p className="case106-meta">Observed in use · Unsolicited service improvement proposal · Not commissioned by the municipality</p></div><figure className="case106-hero-evidence"><img src="/106/whatsapp-mosquitoes.jpg" alt="WhatsApp exchange in Hebrew where a report about mosquitoes at the Yad Labanim dog park is followed by a generic intake request" width={691} height={1536}/><figcaption>Observed municipal 106 WhatsApp intake</figcaption></figure></CaseOpening>
    <section className="rebuild-section rebuild-moment" aria-labelledby="moment-title"><div className="rebuild-label"><CaseLabel id="moment-title">The moment</CaseLabel></div><div className="rebuild-narrative"><p className="rebuild-lead">I had already written the problem and the location.</p><figure className="rebuild-evidence"><img src="/106/whatsapp-mosquitoes.jpg" alt="WhatsApp exchange in Hebrew showing the original resident report" width={691} height={1536}/><figcaption>Observed municipal 106 WhatsApp intake</figcaption></figure><div className="rebuild-annotation"><dl><div><dt>Issue</dt><dd>Mosquitoes</dd></div><div><dt>Request</dt><dd>Pest control</dd></div><div><dt>Location</dt><dd>Yad Labanim dog park</dd></div></dl></div><div className="rebuild-support"><p>I used WhatsApp the way I normally would: I wrote what I needed and where the problem was.</p><p>The automated reply then asked me to describe the issue again.</p></div></div></section>
    <section className="rebuild-section rebuild-why" aria-labelledby="why-title"><div className="rebuild-label"><CaseLabel id="why-title">Why it matters</CaseLabel></div><div className="rebuild-why-grid"><p className="rebuild-lead">The second time it happened, I just didn’t continue.</p><figure className="rebuild-offset-evidence"><img src="/106/whatsapp-repetition.jpg" alt="WhatsApp exchange in Hebrew showing a detailed resident request followed by a generic automated intake request" width={691} height={1536}/><figcaption>A second observed interaction</figcaption></figure><div className="rebuild-support"><p>That made me wonder what happens to reports that stop at this point.</p><p>If a 106 request is only created after the automated intake is completed, repetition like this could mean some reports never make it into the system.</p><p className="case106-caveat">I don’t know whether that’s how Petah Tikva’s backend works. It’s the first thing I’d want to verify.</p></div></div></section>
    <section className="rebuild-section rebuild-split" aria-labelledby="current-better-title"><CaseLabel id="current-better-title">Current → Better</CaseLabel><div className="rebuild-split-stage"><div className="rebuild-side rebuild-current"><h2>Current</h2><ol>{currentFlow.map((item, i)=><li key={item}><span>0{i+1}</span>{item}</li>)}</ol></div><div className="rebuild-side rebuild-better"><h2>Better</h2><ol>{betterFlow.map((item, i)=><li key={item}><span>0{i+1}</span>{item}</li>)}</ol></div></div></section>
    <section className="rebuild-section rebuild-intervention" aria-labelledby="intervention-title"><div className="rebuild-label"><CaseLabel id="intervention-title">The intervention</CaseLabel></div><p className="rebuild-lead">Use the message before asking for it again.</p><div className="rebuild-intervention-grid"><div className="rebuild-raw"><CaseLabel>Resident message:</CaseLabel><div className="case106-message" dir="rtl" lang="he">נשמח להדברת יתושים בגינת כלבים יד לבנים</div></div><div className="rebuild-interpret"><CaseLabel>Interpretation layer</CaseLabel><p>I wouldn’t replace the 106 flow with an AI chatbot.</p><p>I’d add a narrow interpretation step before the existing intake: extract what the resident has already said, check which required fields are still missing, and ask only for those.</p></div><dl className="rebuild-structured"><CaseLabel>Structured information</CaseLabel><div><dt>Issue</dt><dd>Mosquitoes</dd></div><div><dt>Request</dt><dd>Pest control</dd></div><div><dt>Location</dt><dd>Yad Labanim dog park</dd></div><div><dt>Category</dt><dd>Pest control</dd></div><div><dt>Confidence</dt><dd>High</dd></div></dl><div className="rebuild-action"><CaseLabel>Action</CaseLabel><p>Instead of asking for the problem again:</p><blockquote>I understood that you’re reporting mosquitoes at the Yad Labanim dog park. I only need your full name to complete the request.</blockquote><p>If the required identity details are already available, the request could simply move forward.</p></div></div></section>
    <section className="rebuild-section rebuild-checks" aria-labelledby="checks-title"><div className="rebuild-label"><CaseLabel id="checks-title">What I’d check next</CaseLabel></div><div className="rebuild-indexed"><div><p>Before building it:</p><ol>{checksBeforeBuilding.map((item,i)=><li key={item}><span>{String(i+1).padStart(2,"0")}</span>{item}</li>)}</ol></div><div><p>If piloted:</p><ol>{checksIfPiloted.map((item,i)=><li key={item}><span>{String(i+1).padStart(2,"0")}</span>{item}</li>)}</ol></div></div><p className="rebuild-note">I’d keep the extraction constrained: predefined fields, no guessing, and human fallback when confidence is low.</p></section>
    <footer className="case106-ending rebuild-ending"><div className="case106-final"><p>People shouldn’t have to repeat information they’ve already given a service.</p></div><div className="case106-status"><CaseLabel>Status</CaseLabel><p>Unsolicited service improvement proposal.</p><p>Not commissioned, implemented or validated by the Municipality of Petah Tikva.</p><p>The proposal was documented and sent to the municipality for consideration.</p></div><p className="case106-footer">studio golda by ROTKA</p></footer>
  </CaseStudyShell>;
}
