import type { Metadata } from "next";
import { SiteHeader } from "@/components/site-header";
import styles from "./replacement.module.css";

export const metadata: Metadata = { title: "I Already Told You This — Rotem Kasahun" };
const metrics = [["Issue", "Mosquitoes"], ["Request", "Pest control"], ["Location", "Yad Labanim dog park"]];
const timeline = ["Write issue + location", "Generic intake", "Repeat issue", "Complete the remaining fields", "Submit"];
const better = ["Write issue + location", "Use what’s already there", "Ask only for what’s missing", "Submit"];
const checks = ["Which fields are actually mandatory?", "At what point does a WhatsApp message become an official 106 request?", "What information can the existing WhatsApp and service-management setup already receive automatically?", "Which requests should always go to a human?"];

export default function WorkDetailV5() {
  return <div className={styles.root}><div className={styles.chrome}><SiteHeader /></div><main id="main-content"><article className={styles.container}>
    <a className={styles.back} href="/work">← Back to work</a>
    <header className={styles.header}><div className={styles.headerMain}><div className={styles.metaRow}><span className={styles.metaStrong}>A REAL-LIFE ANNOYANCE</span><span>SERVICE DESIGN</span><span>2026</span></div><h1>I Already Told You This</h1><p className={styles.summary}>I told the city what was wrong. I told them where it was. Then their WhatsApp asked me to do it again.</p><p className={styles.muted}>Observed in use · Unsolicited service improvement proposal · Not commissioned by the municipality</p></div><aside className={styles.proof}><p className={styles.metaLabel}>Observed artifact</p><h2>Municipal 106 WhatsApp intake</h2><dl>{metrics.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></aside></header>
    <div className={styles.body}><aside className={styles.left}><div className={styles.sticky}><div><h2 className={styles.metaLabel}>Role</h2><p>Service design observation</p></div><div><h2 className={styles.metaLabel}>Scope</h2><p>Resident-facing WhatsApp intake</p></div><div><h2 className={styles.metaLabel}>Problem</h2><p className={styles.muted}>The interaction asked for information that had already been supplied.</p></div></div></aside><div className={styles.content}>
      <section><h2 className={styles.metaLabel}>What changed</h2><p className={styles.lead}>I had already written the problem and the location.</p><p>I used WhatsApp the way I normally would: I wrote what I needed and where the problem was. The automated reply then asked me to describe the issue again.</p><figure><img src="/106/whatsapp-mosquitoes.jpg" alt="WhatsApp exchange in Hebrew about mosquitoes at the Yad Labanim dog park"/><figcaption>Observed municipal 106 WhatsApp intake</figcaption></figure></section>
      <section><h2 className={styles.metaLabel}>Why it matters</h2><p>The second time it happened, I just didn’t continue.</p><p className={styles.muted}>That made me wonder what happens to reports that stop at this point.</p><p className={styles.muted}>If a 106 request is only created after the automated intake is completed, repetition like this could mean some reports never make it into the system.</p><p className={styles.muted}>I don’t know whether that’s how Petah Tikva’s backend works. It’s the first thing I’d want to verify.</p><figure><img src="/106/whatsapp-repetition.jpg" alt="Second WhatsApp exchange showing a repeated intake request"/><figcaption>A second observed interaction</figcaption></figure></section>
      <section><h2 className={styles.metaLabel}>Current → Better</h2><div className={styles.columns}><div><h3>Current</h3><ol>{timeline.map((x,i)=><li key={x}><b>0{i+1}</b>{x}</li>)}</ol></div><div><h3>Better</h3><ol>{better.map((x,i)=><li key={x}><b>0{i+1}</b>{x}</li>)}</ol></div></div></section>
      <section><h2 className={styles.metaLabel}>The intervention</h2><p className={styles.lead}>Use the message before asking for it again.</p><div className={styles.intervention}><p className={styles.message} dir="rtl" lang="he">נשמח להדברת יתושים בגינת כלבים יד לבנים</p><div><p>I wouldn’t replace the 106 flow with an AI chatbot.</p><p>I’d add a narrow interpretation step before the existing intake: extract what the resident has already said, check which required fields are still missing, and ask only for those.</p></div><dl>{[["Issue","Mosquitoes"],["Request","Pest control"],["Location","Yad Labanim dog park"],["Category","Pest control"],["Confidence","High"]].map(([a,b])=><div key={a}><dt>{a}</dt><dd>{b}</dd></div>)}</dl></div><blockquote>I understood that you’re reporting mosquitoes at the Yad Labanim dog park. I only need your full name to complete the request.</blockquote><p>If the required identity details are already available, the request could simply move forward.</p></section>
      <section><h2 className={styles.metaLabel}>Conclusion</h2><p className={styles.conclusion}>People shouldn’t have to repeat information they’ve already given a service.</p></section>
      <section><h2 className={styles.metaLabel}>What I’d check next</h2><ol className={styles.list}>{checks.map((x,i)=><li key={x}><b>{String(i+1).padStart(2,"0")}</b>{x}</li>)}</ol><p className={styles.status}><strong>Status</strong><br/>Unsolicited service improvement proposal. Not commissioned, implemented or validated by the Municipality of Petah Tikva. The proposal was documented and sent to the municipality for consideration.</p></section>
    </div></div></article></main><footer className={styles.footer}>studio golda by ROTKA</footer></div>;
}
