import { CaseLabel, CaseOpening, CaseStudyShell } from "@/components/case-study";
import { SiteHeader } from "@/components/site-header";
import type { Metadata } from "next";
import styles from "./replacement.module.css";

export const metadata: Metadata = { title: "I Already Told You This — Rotem Kasahun" };
const current = ["Write issue + location", "Generic intake", "Repeat issue", "Complete the remaining fields", "Submit"];
const better = ["Write issue + location", "Use what’s already there", "Ask only for what’s missing", "Submit"];
const before = ["Which fields are actually mandatory?", "At what point does a WhatsApp message become an official 106 request?", "What information can the existing WhatsApp and service-management setup already receive automatically?", "Which requests should always go to a human?"];
const piloted = ["Does it reduce the number of messages needed to submit a request?", "Do more residents complete the flow?", "Can issue and location be extracted accurately enough?"];

export default function Replacement106() {
  return <CaseStudyShell className={styles.page}><div className="golda-header-shell"><SiteHeader /></div><article className={styles.document}><CaseOpening><div className={styles.openingText}><CaseLabel>A real-life annoyance / service design / 2026</CaseLabel><h1><span className="motion-headline-line">I Already Told You This</span></h1><p>I told the city what was wrong.</p><p>I told them where it was.</p><p>Then their WhatsApp asked me to do it again.</p><small>Observed in use · Unsolicited service improvement proposal · Not commissioned by the municipality</small></div><figure className={styles.openingImage}><img src="/106/whatsapp-mosquitoes.jpg" alt="WhatsApp exchange in Hebrew where a report about mosquitoes at the Yad Labanim dog park is followed by a generic intake request" width={691} height={1536}/><figcaption>Observed municipal 106 WhatsApp intake</figcaption></figure></CaseOpening><div className={styles.flow}>
    <div className={styles.primary}><CaseLabel>The moment</CaseLabel><p className={styles.display}>I had already written the problem and the location.</p><figure><img src="/106/whatsapp-mosquitoes.jpg" alt="WhatsApp exchange in Hebrew showing the original resident report" width={691} height={1536}/><figcaption>Observed municipal 106 WhatsApp intake</figcaption></figure><dl><div><dt>Issue</dt><dd>Mosquitoes</dd></div><div><dt>Request</dt><dd>Pest control</dd></div><div><dt>Location</dt><dd>Yad Labanim dog park</dd></div></dl><div className={styles.note}><p>I used WhatsApp the way I normally would: I wrote what I needed and where the problem was.</p><p>The automated reply then asked me to describe the issue again.</p></div></div>
    <div className={styles.statement}><CaseLabel>Why it matters</CaseLabel><p className={styles.display}>The second time it happened, I just didn’t continue.</p><p>That made me wonder what happens to reports that stop at this point.</p><p>If a 106 request is only created after the automated intake is completed, repetition like this could mean some reports never make it into the system.</p><p className="case106-caveat">I don’t know whether that’s how Petah Tikva’s backend works. It’s the first thing I’d want to verify.</p></div>
    <figure className={styles.secondary}><img src="/106/whatsapp-repetition.jpg" alt="WhatsApp exchange in Hebrew showing a detailed resident request followed by a generic automated intake request" width={691} height={1536}/><figcaption>A second observed interaction</figcaption></figure>
    <div className={styles.compare}><CaseLabel>Current → Better</CaseLabel><div><h2>Current</h2><ol>{current.map((x,i)=><li key={x}><span>0{i+1}</span>{x}</li>)}</ol></div><div><h2>Better</h2><ol>{better.map((x,i)=><li key={x}><span>0{i+1}</span>{x}</li>)}</ol></div></div>
    <div className={styles.intervention}><CaseLabel>The intervention</CaseLabel><p className={styles.display}>Use the message before asking for it again.</p><div className={styles.sequence}><div><CaseLabel>Resident message:</CaseLabel><p className={styles.message} dir="rtl" lang="he">נשמח להדברת יתושים בגינת כלבים יד לבנים</p></div><div><CaseLabel>Interpretation layer</CaseLabel><p>I wouldn’t replace the 106 flow with an AI chatbot.</p><p>I’d add a narrow interpretation step before the existing intake: extract what the resident has already said, check which required fields are still missing, and ask only for those.</p></div><dl><CaseLabel>Structured information</CaseLabel><div><dt>Issue</dt><dd>Mosquitoes</dd></div><div><dt>Request</dt><dd>Pest control</dd></div><div><dt>Location</dt><dd>Yad Labanim dog park</dd></div><div><dt>Category</dt><dd>Pest control</dd></div><div><dt>Confidence</dt><dd>High</dd></div></dl><div><CaseLabel>Action</CaseLabel><p>Instead of asking for the problem again:</p><blockquote>I understood that you’re reporting mosquitoes at the Yad Labanim dog park. I only need your full name to complete the request.</blockquote><p>If the required identity details are already available, the request could simply move forward.</p></div></div></div>
    <div className={styles.conclusion}>People shouldn’t have to repeat information they’ve already given a service.</div>
    <aside className={styles.end}><CaseLabel>What I’d check next</CaseLabel><div><p>Before building it:</p><ol>{before.map((x,i)=><li key={x}><span>{String(i+1).padStart(2,"0")}</span>{x}</li>)}</ol></div><div><p>If piloted:</p><ol>{piloted.map((x,i)=><li key={x}><span>{String(i+1).padStart(2,"0")}</span>{x}</li>)}</ol></div><p>I’d keep the extraction constrained: predefined fields, no guessing, and human fallback when confidence is low.</p><small><CaseLabel>Status</CaseLabel> Unsolicited service improvement proposal. Not commissioned, implemented or validated by the Municipality of Petah Tikva. The proposal was documented and sent to the municipality for consideration.</small></aside>
  </div><footer>studio golda by ROTKA</footer></article></CaseStudyShell>;
}
