"use client";
import { useEffect } from "react";
import { SiteHeader } from "@/components/site-header";
import styles from "./replacement.module.css";

export default function WorkDetailV7() {
  useEffect(() => { const onScroll=()=>{ const h=document.documentElement.scrollHeight-innerHeight; const bar=document.querySelector<HTMLElement>(`.${styles.progress}`); if(bar) bar.style.width=(h?Math.min(scrollY/h,1)*100:0)+"%"; }; addEventListener("scroll",onScroll,{passive:true}); onScroll(); return()=>removeEventListener("scroll",onScroll); },[]);
  return <div className={styles.page}><div className={styles.progress}/><div className={styles.chrome}><SiteHeader/></div><main className={`${styles.main} ${styles.case}`}><div className={styles.meta}>A REAL-LIFE ANNOYANCE / SERVICE DESIGN / 2026</div><h1 className={styles.h1}>I Already Told You This</h1><div className={styles.opening}>I told the city what was wrong.<br/>I told them where it was.<br/>Then their WhatsApp asked me to do it again.</div><div className={styles.body}>
    <section className={styles.section}><span className={styles.num}>01</span><h2 className={styles.sectionTitle}>THE MOMENT</h2><p>I had already given them the problem and the location.</p><p>The message was specific. The reply asked for the problem again.</p></section><figure className={styles.full}><img src="/106/whatsapp-mosquitoes.jpg" alt="WhatsApp exchange in Hebrew about mosquitoes at the Yad Labanim dog park"/><figcaption>Observed municipal 106 WhatsApp intake</figcaption></figure>
    <section className={styles.section}><span className={styles.num}>02</span><h2 className={styles.sectionTitle}>WHY IT MATTERS</h2><p>The second time it happened, I just didn’t continue.</p><p>The observed flow raises a question about what happens to reports that stop at this point. I don’t know whether this is how Petah Tikva’s backend works; that is the first thing I’d want to verify.</p></section><figure className={styles.full}><img src="/106/whatsapp-repetition.jpg" alt="Second WhatsApp exchange showing a repeated intake request"/><figcaption>A second observed interaction</figcaption></figure>
    <hr className={styles.separator}/><section className={styles.section}><span className={styles.num}>03</span><h2 className={styles.sectionTitle}>CURRENT → BETTER</h2><p>Resident explains issue and location<br/>→ automated flow asks for information again</p><p>Resident explains issue and location<br/>→ interpretation layer extracts what is already there<br/>→ flow asks only for missing information<br/>→ complete request can move forward</p></section>
    <section className={styles.section}><span className={styles.num}>04</span><h2 className={styles.sectionTitle}>THE INTERVENTION</h2><h3>Add a small AI interpretation layer before the intake flow.</h3><p>The layer would read the resident’s message, extract the information already there, map it to the municipality’s required fields, and check what is still missing. If something is missing, ask only for that. If everything required is already there, move the request forward.</p><p className={styles.logic}>Natural-language message<br/>→ extract information already present<br/>→ map/classify to required categories/fields<br/>→ determine what is missing<br/>→ ask only for missing information<br/>→ if complete, move forward.</p></section>
    <div className={styles.row}><figure><img src="/106/whatsapp-mosquitoes.jpg" alt="Observed WhatsApp message"/></figure><figure><img src="/106/whatsapp-repetition.jpg" alt="Observed repeated WhatsApp intake"/></figure></div><div className={styles.caption}>The same two observed interactions, retained as evidence.</div>
    <section className={styles.section}><span className={styles.num}>05</span><h2 className={styles.sectionTitle}>WHAT I’D CHECK NEXT</h2><ul><li>What fields are mandatory?</li><li>At what point is an official request created?</li><li>What can the current setup receive automatically?</li><li>Which fields still require human handling?</li><li>Can known sender details be reused safely if policy/privacy permits?</li><li>Can landmarks or parks be resolved reliably?</li><li>What validation would be needed for message extraction and completion?</li></ul></section>
    <hr className={styles.separator}/><p className={styles.conclusion}>People shouldn’t have to repeat information they’ve already given a service.</p><p className={styles.status}>Unsolicited service improvement proposal · Sent to the Municipality of Petah Tikva for consideration · Not commissioned, implemented or validated</p>
  </div></main><footer className={styles.footer}>studio golda by ROTKA</footer></div>;
}
